### ISSUE TITLE
bson: slice bounds out of range

### ISSUE THREAD

**Issue by dvyukov** [go-mgo/mgo#116]
The following program crashes with the panic:
```go
package main

import "gopkg.in/mgo.v2/bson"

func main() {
	data := []byte("!\x00\x00\x00\f000000000000000\x00000\xdf0000000\x00")
	bson.Unmarshal(data, make(bson.M))
}
```
```
panic: runtime error: slice bounds out of range [recovered]
	panic: runtime error: slice bounds out of range

goroutine 1 [running]:
gopkg.in/mgo.v2/bson.handleErr(0xc208039f58)
	src/gopkg.in/mgo.v2/bson/bson.go:410 +0x8d
gopkg.in/mgo.v2/bson.(*decoder).readBytes(0xc20803a480, 0xdf30302f, 0x0, 0x0, 0x0)
	src/gopkg.in/mgo.v2/bson/decode.go:824 +0xbd
gopkg.in/mgo.v2/bson.(*decoder).readStr(0xc20803a480, 0x0, 0x0)
	src/gopkg.in/mgo.v2/bson/decode.go:755 +0x54
gopkg.in/mgo.v2/bson.(*decoder).readElemTo(0xc20803a480, 0x4eec80, 0xc20800a440, 0xd4, 0xc20800a40c, 0x0)
	src/gopkg.in/mgo.v2/bson/decode.go:520 +0x30c5
gopkg.in/mgo.v2/bson.(*decoder).readDocTo(0xc20803a480, 0x5127a0, 0xc20803a450, 0x15)
	src/gopkg.in/mgo.v2/bson/decode.go:243 +0xb1b
gopkg.in/mgo.v2/bson.Unmarshal(0xc20803a420, 0x21, 0x30, 0x5127a0, 0xc20803a450, 0x0, 0x0)
	src/gopkg.in/mgo.v2/bson/bson.go:512 +0x27a
main.main()
	bson.go:7 +0xad
```
on commit 3569c88678d88179dcbd68d02ab081cbca3cd4d0

discovered with https://github.com/dvyukov/go-fuzz

**Comment by niemeyer** [comment]
Thanks Dmitry. I need to spend some time looking into go-fuzz.
