### ISSUE TITLE
Error on connect to mongo

### ISSUE THREAD

**Issue by valiknet18** [go-mgo/mgo#178]
Hello everybody, i get error on connect to mongo

```
panic: runtime error: index out of range

goroutine 1 [running]:
main.main()
	/home/valik-pc/.gvm/pkgsets/go1.4/global/src/github.com/valiknet18/AudioSenderTelegramBot/main.go:43 +0x4f2

goroutine 5 [sleep]:
gopkg.in/mgo%2ev2.(*mongoCluster).syncServersLoop(0xc208070200)
	/home/valik-pc/.gvm/pkgsets/go1.4/global/src/gopkg.in/mgo.v2/cluster.go:368 +0x291
created by gopkg.in/mgo%2ev2.newCluster
	/home/valik-pc/.gvm/pkgsets/go1.4/global/src/gopkg.in/mgo.v2/cluster.go:78 +0x20b

goroutine 19 [select]:
net/http.(*persistConn).roundTrip(0xc208096160, 0xc20822ec70, 0x0, 0x0, 0x0)
	/home/valik-pc/.gvm/gos/go1.4/src/net/http/transport.go:1082 +0x7ad
net/http.(*Transport).RoundTrip(0xc208062090, 0xc208035ba0, 0xc208053e60, 0x0, 0x0)
	/home/valik-pc/.gvm/gos/go1.4/src/net/http/transport.go:235 +0x558
net/http.send(0xc208035ba0, 0x7fc7aa331dc8, 0xc208062090, 0x53, 0x0, 0x0)
	/home/valik-pc/.gvm/gos/go1.4/src/net/http/client.go:219 +0x4fc
net/http.(*Client).send(0xc20803d260, 0xc208035ba0, 0x53, 0x0, 0x0)
	/home/valik-pc/.gvm/gos/go1.4/src/net/http/client.go:142 +0x15b
net/http.(*Client).doFollowingRedirects(0xc20803d260, 0xc208035ba0, 0x84c6a0, 0x0, 0x0, 0x0)
	/home/valik-pc/.gvm/gos/go1.4/src/net/http/client.go:367 +0xb25
net/http.(*Client).Post(0xc20803d260, 0xc208053e00, 0x53, 0x7f71f0, 0x21, 0x7fc7aa333208, 0xc208204f20, 0x53, 0x0, 0x0)
	/home/valik-pc/.gvm/gos/go1.4/src/net/http/client.go:441 +0x10d
net/http.(*Client).PostForm(0xc20803d260, 0xc208053e00, 0x53, 0xc2081d3c50, 0x2, 0x0, 0x0)
	/home/valik-pc/.gvm/gos/go1.4/src/net/http/client.go:461 +0x11c
github.com/Syfaro/telegram-bot-api.(*BotAPI).MakeRequest(0xc208052360, 0x7b6fb0, 0xa, 0xc2081d3c50, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/home/valik-pc/.gvm/pkgsets/go1.4/global/src/github.com/Syfaro/telegram-bot-api/methods.go:197 +0x1ee
github.com/Syfaro/telegram-bot-api.(*BotAPI).GetUpdates(0xc208052360, 0x34058fc4, 0x0, 0x3c, 0x0, 0x0, 0x0, 0x0, 0x0)
	/home/valik-pc/.gvm/pkgsets/go1.4/global/src/github.com/Syfaro/telegram-bot-api/methods.go:997 +0x671
github.com/Syfaro/telegram-bot-api.func·001()
	/home/valik-pc/.gvm/pkgsets/go1.4/global/src/github.com/Syfaro/telegram-bot-api/updates.go:14 +0x58
created by github.com/Syfaro/telegram-bot-api.(*BotAPI).UpdatesChan
	/home/valik-pc/.gvm/pkgsets/go1.4/global/src/github.com/Syfaro/telegram-bot-api/updates.go:30 +0x12e

goroutine 12 [IO wait]:
net.(*pollDesc).Wait(0xc208012220, 0x72, 0x0, 0x0)
	/home/valik-pc/.gvm/gos/go1.4/src/net/fd_poll_runtime.go:84 +0x47
net.(*pollDesc).WaitRead(0xc208012220, 0x0, 0x0)
	/home/valik-pc/.gvm/gos/go1.4/src/net/fd_poll_runtime.go:89 +0x43
net.(*netFD).Read(0xc2080121c0, 0xc20803cf00, 0x24, 0x24, 0x0, 0x7fc7aa331b60, 0xc20800b4c8)
	/home/valik-pc/.gvm/gos/go1.4/src/net/fd_unix.go:242 +0x40f
net.(*conn).Read(0xc20802e060, 0xc20803cf00, 0x24, 0x24, 0x0, 0x0, 0x0)
	/home/valik-pc/.gvm/gos/go1.4/src/net/net.go:121 +0xdc
gopkg.in/mgo%2ev2.fill(0x7fc7aa332fb8, 0xc20802e060, 0xc20803cf00, 0x24, 0x24, 0x0, 0x0)
	/home/valik-pc/.gvm/pkgsets/go1.4/global/src/gopkg.in/mgo.v2/socket.go:533 +0x75
gopkg.in/mgo%2ev2.(*mongoSocket).readLoop(0xc20806a1c0)
	/home/valik-pc/.gvm/pkgsets/go1.4/global/src/gopkg.in/mgo.v2/socket.go:550 +0x126
created by gopkg.in/mgo%2ev2.newSocket
	/home/valik-pc/.gvm/pkgsets/go1.4/global/src/gopkg.in/mgo.v2/socket.go:197 +0x3d3

goroutine 11 [sleep]:
gopkg.in/mgo%2ev2.(*mongoServer).pinger(0xc20806a0e0, 0x1)
	/home/valik-pc/.gvm/pkgsets/go1.4/global/src/gopkg.in/mgo.v2/server.go:296 +0x169
created by gopkg.in/mgo%2ev2.newServer
	/home/valik-pc/.gvm/pkgsets/go1.4/global/src/gopkg.in/mgo.v2/server.go:89 +0x194

goroutine 16 [IO wait]:
net.(*pollDesc).Wait(0xc2080124c0, 0x72, 0x0, 0x0)
	/home/valik-pc/.gvm/gos/go1.4/src/net/fd_poll_runtime.go:84 +0x47
net.(*pollDesc).WaitRead(0xc2080124c0, 0x0, 0x0)
	/home/valik-pc/.gvm/gos/go1.4/src/net/fd_poll_runtime.go:89 +0x43
net.(*netFD).Read(0xc208012460, 0xc208066800, 0x400, 0x400, 0x0, 0x7fc7aa331b60, 0xc20822ec68)
	/home/valik-pc/.gvm/gos/go1.4/src/net/fd_unix.go:242 +0x40f
net.(*conn).Read(0xc20802e0d8, 0xc208066800, 0x400, 0x400, 0x0, 0x0, 0x0)
	/home/valik-pc/.gvm/gos/go1.4/src/net/net.go:121 +0xdc
crypto/tls.(*block).readFromUntil(0xc20803d470, 0x7fc7aa333260, 0xc20802e0d8, 0x5, 0x0, 0x0)
	/home/valik-pc/.gvm/gos/go1.4/src/crypto/tls/conn.go:454 +0xe6
crypto/tls.(*Conn).readRecord(0xc2080a2000, 0x17, 0x0, 0x0)
	/home/valik-pc/.gvm/gos/go1.4/src/crypto/tls/conn.go:539 +0x2da
crypto/tls.(*Conn).Read(0xc2080a2000, 0xc208011000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
	/home/valik-pc/.gvm/gos/go1.4/src/crypto/tls/conn.go:904 +0x166
net/http.noteEOFReader.Read(0x7fc7aa337c90, 0xc2080a2000, 0xc2080961b8, 0xc208011000, 0x1000, 0x1000, 0x6f7060, 0x0, 0x0)
	/home/valik-pc/.gvm/gos/go1.4/src/net/http/transport.go:1270 +0x6e
net/http.(*noteEOFReader).Read(0xc208204720, 0xc208011000, 0x1000, 0x1000, 0xc208014000, 0x0, 0x0)
	<autogenerated>:125 +0xd4
bufio.(*Reader).fill(0xc208053740)
```

Help plz resolve this problem, 
Connection file
https://github.com/valiknet18/AudioSenderTelegramBot/blob/master/session.go

**Comment by niemeyer** [comment]
This is a panic and error coming from your own code, which does not match the code you link at the end. See the first few lines of the backtrace.
