### ISSUE TITLE
Timeouts handling?

### ISSUE THREAD

**Issue by lud4ik** [go-mgo/mgo#214]
In our application we have ~ 200 goroutines in form of:
```
goroutine 15131535 [IO wait, 2913 minutes]:
net.runtime_pollWait(0x7f56c7e9b578, 0x72, 0xc82000e1f0)
	/usr/local/go/src/runtime/netpoll.go:157 +0x60
net.(*pollDesc).Wait(0xc824b0be90, 0x72, 0x0, 0x0)
	/usr/local/go/src/net/fd_poll_runtime.go:73 +0x3a
net.(*pollDesc).WaitRead(0xc824b0be90, 0x0, 0x0)
	/usr/local/go/src/net/fd_poll_runtime.go:78 +0x36
net.(*netFD).Read(0xc824b0be30, 0xc832eeb890, 0x24, 0x24, 0x0, 0x7f56cd541050, 0xc82000e1f0)
	/usr/local/go/src/net/fd_unix.go:232 +0x23a
net.(*conn).Read(0xc838e24b38, 0xc832eeb890, 0x24, 0x24, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/net.go:172 +0xe4
gopkg.in/mgo%2ev2.fill(0x7f56cd54a370, 0xc838e24b38, 0xc832eeb890, 0x24, 0x24, 0x0, 0x0)
	/opt/buildAgent/work/ace81f004f3483d2/vendor/src/gopkg.in/mgo.v2/socket.go:530 +0x6c
gopkg.in/mgo%2ev2.(*mongoSocket).readLoop(0xc830942b60)
	/opt/buildAgent/work/ace81f004f3483d2/vendor/src/gopkg.in/mgo.v2/socket.go:547 +0x132
created by gopkg.in/mgo%2ev2.newSocket
	/opt/buildAgent/work/ace81f004f3483d2/vendor/src/gopkg.in/mgo.v2/socket.go:194 +0x402

```

```
goroutine 15131541 [IO wait, 12 minutes]:
net.runtime_pollWait(0x7f56c7efb888, 0x72, 0xc82000e1f0)
	/usr/local/go/src/runtime/netpoll.go:157 +0x60
net.(*pollDesc).Wait(0xc831f53720, 0x72, 0x0, 0x0)
	/usr/local/go/src/net/fd_poll_runtime.go:73 +0x3a
net.(*pollDesc).WaitRead(0xc831f53720, 0x0, 0x0)
	/usr/local/go/src/net/fd_poll_runtime.go:78 +0x36
net.(*netFD).Read(0xc831f536c0, 0xc837ea6c90, 0x24, 0x24, 0x0, 0x7f56cd541050, 0xc82000e1f0)
	/usr/local/go/src/net/fd_unix.go:232 +0x23a
net.(*conn).Read(0xc82d2439b0, 0xc837ea6c90, 0x24, 0x24, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/net.go:172 +0xe4
gopkg.in/mgo%2ev2.fill(0x7f56cd54a370, 0xc82d2439b0, 0xc837ea6c90, 0x24, 0x24, 0x0, 0x0)
	/opt/buildAgent/work/ace81f004f3483d2/vendor/src/gopkg.in/mgo.v2/socket.go:530 +0x6c
gopkg.in/mgo%2ev2.(*mongoSocket).readLoop(0xc82b3b37a0)
	/opt/buildAgent/work/ace81f004f3483d2/vendor/src/gopkg.in/mgo.v2/socket.go:547 +0x132
created by gopkg.in/mgo%2ev2.newSocket
	/opt/buildAgent/work/ace81f004f3483d2/vendor/src/gopkg.in/mgo.v2/socket.go:194 +0x402
```

Line 194:
```
func newSocket(server *mongoServer, conn net.Conn, timeout time.Duration) *mongoSocket {
   go socket.readLoop()
   ...
}

...
func (socket *mongoSocket) readLoop() {
	p := make([]byte, 36) // 16 from header + 20 from OP_REPLY fixed fields
	s := make([]byte, 4)
	conn := socket.conn // No locking, conn never changes.
	for {
		// XXX Handle timeouts, , etc
		err := fill(conn, p) 
...
```
How to set properly timeout? Will it help in this case?

**Comment by niemeyer** [comment]
The way to tweak the reading and writing timeouts is via `SetSocketTimeout`, or at DialWithInfo time via the Timeout option. If you're using an up-to-date version of mgo, the default when using Dial itself is one minute. How are you connecting to the database?

The TODO there is out of date. Have a look around that logic and you should see the manipulation of deadlines in place.

By the way, please ensure you have an up-to-date version of mgo so we're both talking about the same code base.

**Comment by lud4ik** [comment]
Version latest
Connect through:
"""
mongoSession, err := mgo.DialWithTimeout(cConfig.MongoDBDSN, 5*time.Second)
"""
After we use 
```
mongoSession.Copy()
```

**Comment by lud4ik** [comment]
I guess it's waiting on this read
```
func fill(r net.Conn, b []byte) error {
	l := len(b)
	n, err := r.Read(b)    // WAIT
	for n != l && err == nil {
		var ni int
		ni, err = r.Read(b[n:])
		n += ni
	}
	return err
}
```

**Comment by niemeyer** [comment]
Yes, it may well be waiting on this read, and that's not a bug. The timeout only affects sockets that are indeed attempting to read something, and the driver knows when to expect data out of a socket or not. Have a look at your connection statistics [mgo.GetStats](http://gopkg.in/mgo.v2#GetStats).. if you have 200 sockets alive, but a dormant application doing nothing, this may well happen without it being a bug.

**Comment by niemeyer** [comment]
> I guess this was a TODO = "XXX"

Right, and it was done long ago. Timeout support is in place already, as mentioned above.

**Comment by niemeyer** [comment]
Yes, that's all fine. Why do you believe there's a bug?

**Comment by niemeyer** [comment]
If you have some further details about why this would be a bug, please feel free to reopen the issue with them.
