### ISSUE TITLE
Panic on Bulk.Run with unique indexes on 3.2

### ISSUE THREAD

**Issue by ernado** [go-mgo/mgo#275]
```bash
# mongod --version
db version v3.2.6
git version: 05552b562c7a0b3143a729aaa0838e558dc49b25
OpenSSL version: OpenSSL 1.0.2g-fips  1 Mar 2016
allocator: tcmalloc
modules: none
build environment:
    distmod: ubuntu1404
    distarch: x86_64
    target_arch: x86_64

```
Stack trace:
```
goroutine 1 [running]:
panic(0x57a140, 0xc42000c160)
	/usr/local/go/src/runtime/panic.go:500 +0x18c
gopkg.in/mgo%2ev2.(*Collection).writeOp(0xc420017440, 0x562c20, 0xc420ccca80, 0x40f900, 0x0, 0x0, 0x0)
	/go/src/gopkg.in/mgo.v2/session.go:4529 +0x5c6
gopkg.in/mgo%2ev2.(*Bulk).runInsert(0xc420ce1dd0, 0xc420014a00, 0xc420cbb8c0, 0xc420cbb8e0, 0x0)
	/go/src/gopkg.in/mgo.v2/bulk.go:310 +0xb9
gopkg.in/mgo%2ev2.(*Bulk).Run(0xc420ce1dd0, 0x2, 0x2, 0x56abc0)
	/go/src/gopkg.in/mgo.v2/bulk.go:283 +0x2af
main.main()
	/<...>/main.go:66 +0x75d
```
Index:
```
> db.import.ensureIndex({id: 1}, {unique: true})
{
	"createdCollectionAutomatically" : false,
	"numIndexesBefore" : 1,
	"numIndexesAfter" : 2,
	"ok" : 1
}
```
My code:
```go
	// ...
	reader := msgp.NewReader(f)
	logrus.Println("preparing")
	b.Unordered()
	var count int
	var read int
	for {
		// reading msgpack entry from file
		if err := entry.DecodeMsg(reader); err != nil {
			if err != io.EOF {
				logrus.Error(err)
			}
			break
		}
		read++
		mapping, ok := mappings[entry.Type]
		if !ok {
			logrus.Warn("not found", entry.Type)
                        continue
		}
		count++
                // Map returns bson.M generated from entry with rules from mapping
		b.Insert(mapping.Map(entry))
	}
	if info, err := b.Run(); err != nil {
		logrus.Fatal(err)
	}
	logrus.Println("OK")
```
After dropping index all works fine. Installed via `go get -u gopkg.in/mgo.v2`. 
Possible cause of error - I have duplicates for unique index in this bulk, so mgo is trying to process errors and fails.

**Comment by niemeyer** [comment]
Thank you very much for the report.

I'll get that fixed shortly.
