### ISSUE TITLE
Interface Setter/Getter

### ISSUE THREAD

**Issue by firewut** [go-mgo/mgo#322]
@niemeyer, hello once again 💃 It's been a while, but I got a problem with custom structs SetBSON/GetBSON.
The example is [https://play.golang.org/p/QuwhUDvEDr](https://play.golang.org/p/QuwhUDvEDr)

I encountered this error

```bash
panic: interface conversion: interface is nil, not bson.Setter [recovered]
	panic: interface conversion: interface is nil, not bson.Setter

goroutine 1 [running]:
panic(0x17f9a0, 0xc420146780)
	/usr/local/opt/go/libexec/src/runtime/panic.go:500 +0x1a1
gopkg.in/mgo.v2/bson.handleErr(0xc420163d08)
	/Users/zwut/projects/go/tmp/mgo-map/.vendor/src/gopkg.in/mgo.v2/bson/bson.go:459 +0x260
panic(0x17f9a0, 0xc420146780)
	/usr/local/opt/go/libexec/src/runtime/panic.go:458 +0x243
gopkg.in/mgo.v2/bson.getSetter(0x268140, 0x184280, 0x184280, 0xc42014aa30, 0x194, 0x170d00, 0x268140)
	/Users/zwut/projects/go/tmp/mgo-map/.vendor/src/gopkg.in/mgo.v2/bson/decode.go:118 +0xe2
gopkg.in/mgo.v2/bson.(*decoder).readDocTo(0xc420163ca0, 0x184280, 0xc42014aa30, 0x194)
	/Users/zwut/projects/go/tmp/mgo-map/.vendor/src/gopkg.in/mgo.v2/bson/decode.go:137 +0x102
gopkg.in/mgo.v2/bson.(*decoder).readElemTo(0xc420163ca0, 0x184280, 0xc42014aa30, 0x194, 0xc42014aa03, 0x100)
	/Users/zwut/projects/go/tmp/mgo-map/.vendor/src/gopkg.in/mgo.v2/bson/decode.go:450 +0x2d69
gopkg.in/mgo.v2/bson.(*decoder).readSliceDoc(0xc420163ca0, 0x268140, 0x16daa0, 0x268140, 0x16daa0)
	/Users/zwut/projects/go/tmp/mgo-map/.vendor/src/gopkg.in/mgo.v2/bson/decode.go:348 +0x20f
gopkg.in/mgo.v2/bson.(*decoder).readElemTo(0xc420163ca0, 0x16daa0, 0xc420146560, 0x197, 0x16da04, 0xc420146500)
	/Users/zwut/projects/go/tmp/mgo-map/.vendor/src/gopkg.in/mgo.v2/bson/decode.go:496 +0x22f8
gopkg.in/mgo.v2/bson.(*decoder).readDocTo(0xc420163ca0, 0x18f620, 0xc420146540, 0x199)
	/Users/zwut/projects/go/tmp/mgo-map/.vendor/src/gopkg.in/mgo.v2/bson/decode.go:256 +0x64e
gopkg.in/mgo.v2/bson.Unmarshal(0xc42017e035, 0x59, 0x88, 0x168080, 0xc420146540, 0x0, 0x0)
	/Users/zwut/projects/go/tmp/mgo-map/.vendor/src/gopkg.in/mgo.v2/bson/bson.go:563 +0x1c2
gopkg.in/mgo%2ev2.(*Query).One(0xc420158300, 0x168080, 0xc420146540, 0x0, 0x0)
	/Users/zwut/projects/go/tmp/mgo-map/.vendor/src/gopkg.in/mgo.v2/session.go:3126 +0x2a4
main.main()
	/Users/zwut/projects/go/tmp/mgo-map/.vendor/src/project/main.go:110 +0x5c7
exit status 2
```

As I suppose - that should work, but maybe I'm missing something :D

**Comment by niemeyer** [comment]
This doesn't work.. there's no way mgo can tell what the concrete type is to then call its SetBSON method given only an interface which might unmarshal into anything that satisfies it.
