### ISSUE TITLE
Rescursive bson.MarshalJSON to bson.D and db.runCommand

### ISSUE THREAD

**Issue by arvenil** [go-mgo/mgo#431]
I'm having some trouble related to `bson.MarshalJSON`,  `bson.D` and `runCommand`.

I think context is necessary here as I'm not really sure how to approach the problem, so please bear with me.

I'm trying to run `explain` over a result from `system.profile`. According to http://stackoverflow.com/questions/43255249/explain-on-a-query-from-profiler I can just grab the query from `system.profile`, then append `explain` to it and run it as `runCommand`. This works for mongo shell. Works also with this driver (yey!). However I need also to transfer/store the query as string so I `bson.MarshalJSON` it. Here starts problems. Let's make the story shorter, here is example code (scroll to execution result, it's gonna be easier to understand):

```go
package main

import (
	"fmt"
	"time"

	"gopkg.in/mgo.v2"
	"gopkg.in/mgo.v2/bson"
)

type SystemProfile struct {
	Op    string `bson:"op"`
	Ns    string `bson:"ns"`
	Query bson.D `bson:"query"`
}

func main() {
	// create connection
	dsn := "127.0.0.1:27017"
	dialInfo, err := mgo.ParseURL(dsn)
	if err != nil {
		panic(err)
	}
	session, err := mgo.DialWithInfo(dialInfo)
	if err != nil {
		panic(err)
	}
	defer session.Close()

	// run some query
	type Person struct {
		ID        bson.ObjectId `bson:"_id,omitempty"`
		Name      string
		Phone     string
		Timestamp time.Time
	}
	p := Person{}
	err = session.DB("test").C("people").Find(bson.M{"name": "Ale"}).Select(bson.M{"phone": 0}).One(&p)
	if err != nil {
		panic(err)
	}

	// get profile for this query
	collection := session.DB(dialInfo.Database).C("system.profile")
	var docs []SystemProfile
	err = collection.Find(bson.M{"op": "query", "ns": "test.people"}).All(&docs)
	if err != nil {
		panic(err)
	}

	doc := docs[0]
	jsonQueryB, err := bson.MarshalJSON(doc.Query)
	if err != nil {
		panic(err)
	}
	jsonQueryS := string(jsonQueryB)
	fmt.Printf("json query: `%s`\n", jsonQueryS)

	// convert it back to byte and to bson.D because the order is important
	jsonQueryB = []byte(jsonQueryS)
	query := bson.D{}
	err = bson.UnmarshalJSON(jsonQueryB, &query)
	if err != nil {
		panic(err)
	}

	explainCmd := bson.D{
		{
			Name:  "explain",
			Value: query,
		},
	}

	result := bson.M{}
	err = session.DB(dialInfo.Database).Run(explainCmd, &result)
	if err != nil {
		panic(err)
	}
	fmt.Println("result: ", result)
}
```
and the result
```term
$ go run main.go
json query: `[{"Name":"find","Value":"people"},{"Name":"filter","Value":[{"Name":"name","Value":"Ale"}]},{"Name":"projection","Value":[{"Name":"phone","Value":0}]},{"Name":"skip","Value":0},{"Name":"limit","Value":1},{"Name":"batchSize","Value":1},{"Name":"singleBatch","Value":true}]
`
panic: Failed to parse: filter: [ { Name: "name", Value: "Ale" } ]. 'filter' field must be of BSON type object.

goroutine 1 [running]:
main.main()
        main.go:77 +0xe64
exit status 2

```

Sooooo... as you can see if I use `bson.MarshalJSON` to `bson.D` it also converts nested values to `bson.D` (e.g. `filter` key above), but runCommand doesn't handle that and I get query error `Failed to parse: filter: [ { Name: "name", Value: "Ale" } ]. 'filter' field must be of BSON type object.`.

I use `bson.D` because order for `explain` cmd for `runCommand` is important. If I use `bson.M` I will get:
```term
 go run main.go
json query: `{"batchSize":1,"filter":{"name":"Ale"},"find":"people","limit":1,"projection":{"phone":0},"singleBatch":true,"skip":0}
`
panic: Explain failed due to unknown command: skip

goroutine 1 [running]:
main.main()
       main.go:77 +0xe18
exit status 2
```
Where `skip` part is just random key as order of elements is not kept.

So this leaves me with `bson.D` as the only option to use. So, I tried then `bson.Marshal` instead of `bson.MarshalJSON` and this works, the problem is I don't think it's safe to convert it to string representation? It's not readable for humans and it's still binary blob if I'm not mistaken so bad it gets corrupted when copied by hand. In other words I can't use it.

However this makes me think that problem is with `runCommand` as maybe it should know passing `bson.D` directly to mongo is not a good idea, instead it should be converted back to object.

Thoughts? Questions? Workarounds? Ideas? :)

**Comment by arvenil** [comment]
Ok, I thought I'm gonna outsmart it at least a little bit by first `bson.MarhshalJSON` and `bson.UnmarhshalJSON` for store/transfer as `string` and then with the unmarshaled value simply `bson.Marshal` and `bson.Unmarshal` to get a value passable to `runCommand`.... but it didn't worked 🤔 

So, it turns out `bson.MarhshalJSON` and `bson.UnmarhshalJSON` corrupts data so it's not the same before and after marshal and unmarshal 😨 

```go
package main

import (
	"fmt"

	"gopkg.in/mgo.v2/bson"
)

func main() {
	org := bson.D{
		{
			Name:  "find",
			Value: "people",
		},
		{
			Name: "filter",
			Value: bson.D{
				{
					Name:  "name",
					Value: "Ale",
				},
			},
		},
	}

	var broken bson.D
	jsonB, err := bson.MarshalJSON(org)
	if err != nil {
		panic(err)
	}
	err = bson.UnmarshalJSON(jsonB, &broken)
	if err != nil {
		panic(err)
	}

	fmt.Printf("org    %#+v\n", org)
	fmt.Printf("broken %#+v\n", broken)
}
```

```console
org    bson.D{bson.DocElem{Name:"find", Value:"people"}, bson.DocElem{Name:"filter", Value:bson.D{bson.DocElem{Name:"name", Value:"Ale"}}}}
broken bson.D{bson.DocElem{Name:"find", Value:"people"}, bson.DocElem{Name:"filter", Value:[]interface {}{map[string]interface {}{"Name":"name", "Value":"Ale"}}}}

```


https://demo.upper.io/p/e2a1f63f9b06d546a1492630d2f8256ca0549b74

**Comment by arvenil** [comment]
Of course perfect solution would be if `bson.UnmarshalJSON` would kept order e.g. by unmarshaling all objects to `bson.D`.
