### ISSUE TITLE
got panic when cluster check isMaster with single mongo server mode 

### ISSUE THREAD

**Issue by pertgame** [go-mgo/mgo#442]
I got the following panic when running my program. It's happened un-predicable,  Its' works fine for days sometime.

panic: interface conversion: *mgo.isMasterResult is not bson.Setter: missing method SetBSON [recovered]
        panic: interface conversion: *mgo.isMasterResult is not bson.Setter: missing method SetBSON
        
goroutine 49479 [running]:
panic(0x852460, 0xc4200bca40)
        /usr/local/go/src/runtime/panic.go:500 +0x1a1
gopkg.in/mgo.v2/bson.handleErr(0xc420679650)
        /root/go/sched/src/gopkg.in/mgo.v2/bson/bson.go:459 +0x260 
panic(0x852460, 0xc4200bca40)
        /usr/local/go/src/runtime/panic.go:458 +0x243 
gopkg.in/mgo.v2/bson.getSetter(0xcc56e0, 0x8151c0, 0x8151c0, 0xc4200ce750, 0x16, 0x194, 0x14)
        /root/go/sched/src/gopkg.in/mgo.v2/bson/decode.go:118 +0xe2
gopkg.in/mgo.v2/bson.(*decoder).readDocTo(0xc4206795e8, 0x8151c0, 0xc4200ce750, 0x16)
        /root/go/sched/src/gopkg.in/mgo.v2/bson/decode.go:137 +0x102 
gopkg.in/mgo.v2/bson.Unmarshal(0xc42015a8c0, 0x9e, 0x9e, 0x8151c0, 0xc4200ce750, 0x0, 0x0)
        /root/go/sched/src/gopkg.in/mgo.v2/bson/bson.go:563 +0x1c2 
gopkg.in/mgo%2ev2.(*Database).run(0xc420679990, 0xc42015e2a0, 0x84b7a0, 0xc42062e7c0, 0x8151c0, 0xc4200ce750, 0x6
1020e, 0xc4201351c0) 
        /root/go/sched/src/gopkg.in/mgo.v2/session.go:3269 +0x2d3 
gopkg.in/mgo%2ev2.(*Database).Run(0xc420679990, 0x82b120, 0xc4207037c0, 0x8151c0, 0xc4200ce750, 0x0, 0x0)
        /root/go/sched/src/gopkg.in/mgo.v2/session.go:656 +0xe9
gopkg.in/mgo%2ev2.(*Session).Run(0xc4206304e0, 0x82b120, 0xc4207037c0, 0x8151c0, 0xc4200ce750, 0x6009c3, 0xc42013
51c0)
        /root/go/sched/src/gopkg.in/mgo.v2/session.go:2014 +0x8b
gopkg.in/mgo%2ev2.(*mongoCluster).isMaster(0xc42006a100, 0xc42015e2a0, 0xc4200ce750, 0xc42015e2a0, 0xc420703700)
        /root/go/sched/src/gopkg.in/mgo.v2/cluster.go:147 +0xd7
gopkg.in/mgo%2ev2.(*mongoCluster).syncServer(0xc42006a100, 0xc42015e1c0, 0xf, 0xc420700990, 0xc42015e1c0, 0x0, 0x
0, 0xc4201320a0)
        /root/go/sched/src/gopkg.in/mgo.v2/cluster.go:196 +0x469
gopkg.in/mgo%2ev2.(*mongoCluster).syncServersIteration.func1.1(0xc420703700, 0xc4201a41c0, 0xf, 0xc420703710, 0x0
, 0xc4207008d0, 0xc42006a100, 0xc420700900, 0xc420700930, 0x0, ...)
        /root/go/sched/src/gopkg.in/mgo.v2/cluster.go:518 +0x1d6
created by gopkg.in/mgo%2ev2.(*mongoCluster).syncServersIteration.func1
        /root/go/sched/src/gopkg.in/mgo.v2/cluster.go:540 +0x15c

**Comment by JodeZer** [comment]
When running `isMaster` cammand, outt is Ptr to `isMasterResult` which does not impl `bson.Setter` , thus ,`style` shoule be `setterNone` and return nil. However, call to `setterStyle` did not return the right val and let the code goto last line ,then cause a panic.
```go

func getSetter(outt reflect.Type, out reflect.Value) Setter {
	style := setterStyle(outt)
	if style == setterNone {
		return nil
	}
	if style == setterAddr {
		if !out.CanAddr() {
			return nil
		}
		out = out.Addr()
	} else if outt.Kind() == reflect.Ptr && out.IsNil() {
		out.Set(reflect.New(outt.Elem()))
	}
	return out.Interface().(Setter)
}

```

setterStyle is in this way, and seems to be thread safe. l cant figure out what happened to the map called `setterStyles`.

```go
func setterStyle(outt reflect.Type) int {
	setterMutex.RLock()
	style := setterStyles[outt]
	setterMutex.RUnlock()
	if style == setterUnknown {
		setterMutex.Lock()
		defer setterMutex.Unlock()
		if outt.Implements(setterIface) {
			setterStyles[outt] = setterType
		} else if reflect.PtrTo(outt).Implements(setterIface) {
			setterStyles[outt] = setterAddr
		} else {
			setterStyles[outt] = setterNone
		}
		style = setterStyles[outt]
	}
	return style
}
```

**Comment by JodeZer** [comment]
But l think 
```go
if i, ok := out.Interface().(Setter); !ok {
      return nil
} else {
      return i
}
```
can solve that provisionally
:)

**Comment by pertgame** [comment]
@JodeZer 这位仁兄来自上海，应该能看中文吧，我英文能力有限，就中文表达吧。
bson这块代码我反复研究了，也加了不少log，最后发现在getSetter的时候，setterTypes这个map出现了异常，之前存放到这个map里面的type，在后来的setterTypel的时候找不到了（默认值变成了setterUnknown）,但是在重新判断setter类型并复制给map的时候也没有成功，style任然是unkonwn，所以再外层类型断言的时候就panic了。
另外，相似的情况发生在了，bson的structMap结构中，bson在decode的时候，已处理的类型反解出来的成员key会保存在structInfo中的FieldsMap中，对于已经之前已经正常处理的类型，在后面的运行中，structInfo中的FieldsMap突然没有任何数据了，导致解析bson的时候，各个字段都解不到正确的值，从而导致上层的各种异常。
从这2个情况来看，貌似还是map数据结构导致逻辑不对了，但是map里面的数据到底是什么原因发生的问题，仍然不能确定。这个map如果不加读写所是可能导致这个问题的，但是出问题的map都是加了读写锁。或者是我访问的mongodb版本太高（3.2），mgo支持到3.0，或者是我go版本太高1.7。
我现在采用的方式是在mgo里面把setterTypes和structMap弃用，每次使用的时候重新计算一遍需要的数据，不做内存缓存，目前运行了几天，暂时正常。
