### ISSUE TITLE
copy new session crash

### ISSUE THREAD

**Issue by pertgame** [go-mgo/mgo#550]
In my program, each action to mgo will copy a new session, and defer to close the new session after mgo-operation, like this:

func doInsert(){
 session, coll := GetNewSession()
 defer session.Close()
 coll.Insert()
}

the backtrace like this：

goroutine 110 [running]:
DataServer/vendor/gopkg.in/mgo%2ev2.(*Session).Copy(0x0, 0xc4204c31c0)
    /xx/xx/xx/xx/xx/vendor/gopkg.in/mgo.v2/session.go:1589 +0x22
DataServer/db.GetNewSession(0x9ea8d2, 0xc, 0xc420268210, 0xc5c5bf)
    /xx/xx/xx/xx/xx/db/mongo.go:70 +0x31
DataServer/db.LoadRoomRecord(0x2c03f8b1f94e000, 0x0, 0x0, 0x0)
    /xx/xx/xx/xx/xx/db/mongo.go:167 +0x6f

------------GetNewSession：
func GetNewSession(collection string) (session *mgo.Session, coll *mgo.Collection) {
	session = m_session.Copy()
	coll = session.DB(conf.GetMongoDBName()).C(collection)
	return session, coll
}

---crash here:
func (s *Session) Copy() *Session {
	s.m.Lock()   ----------line 1589
	scopy := copySession(s, true)
	s.m.Unlock()
	scopy.Refresh()
	return scopy
}

my program runs well in most of time,  but crash at an unpredictable time .
I have no idea what's going on here?  too many sessions or tcp connections to mongodb? no more session could allocate? could anybody give me a hand?

**Comment by JodeZer** [comment]
have u check if the var m_session is not nil or the init of m_session is non-error?

**Comment by pertgame** [comment]
Hi @JodeZer , I'v already solved this problem. The crash is cause by the reaching max connection limit of mongodb, I found it in the log of mongodb. thanks a lot!
